import { Dimensions, StyleSheet } from "react-native";
import theme from "../../appStyles";

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  contentContainer: {
    flex: 2,
    alignSelf: "center",
    justifyContent: "center",
    borderRadius: 20,
    paddingLeft: 20,
    paddingRight: 20,
  },
  materialIconTextbox: {
    marginTop: 10,
  },
  image1: {
    height: 120,
    alignSelf: "center",
  },
  inputWrapper: {
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginTop: 30,
    alignSelf: "center",
    justifyContent: "center",
    borderColor: "#000000",
    borderWidth: 2,
  },
  matButton: {
    color: "#FFFFFF",
    padding: 10,
    marginTop: 30,
    alignSelf: "center",
  },
  inputStyle: {
    color: theme.TEXT_LIGHT,
    marginLeft: 16,
    paddingRight: 5,
    fontSize: 16,
    alignSelf: "stretch",
    flex: 1,
    lineHeight: 16,
    borderBottomWidth: 1,
    borderColor: "#D9D5DC",
    paddingTop: 14,
    paddingBottom: 8,
    borderRadius: 10,
  },
  textStyle: {
    textTransform: "capitalize",
  },
  iconStyle: {
    color: theme?.PRIMARY_COLOR,
    fontSize: 24,
    paddingLeft: 8,
  },
  inputBlock: {
    height: 40,
    width: Dimensions.get("window").width / 1.4,
    marginTop: 20,
    backgroundColor: "rgba(255,255,255,1)",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
  },
  icon: {
    color: theme?.PRIMARY_COLOR,
    fontSize: 126,
    alignSelf: "center",
  },
  pencilIcon: {
    color: theme?.PRIMARY_COLOR,
    fontSize: 30,
    marginLeft: "2%",
    marginTop: "-1%",
    alignSelf: "center",
    backgroundColor: theme?.THEME_LIGHT,
    borderColor: theme?.PRIMARY_COLOR,
    borderWidth: 2,
    borderRadius: 50,
  },
  hideButton: {
    marginTop: 30,
    alignSelf: "center",
    borderRadius: 100,
  },
  closeIcon: {
    color: theme.TEXT_LIGHT,
    textDecorationLine: "underline",
  },
  badge: {
    marginLeft: 10,
    marginRight: 10,
    fontSize: 10,
    alignSelf: "center",
    borderRadius: 10,
    paddingLeft: 6,
    paddingRight: 6,
    paddingTop: 3,
    paddingBottom: 3,
  },
});
